### ISSUE TITLE
(removed)

### ISSUE THREAD

**Issue by KruseLuds** [claudobahn/weewx-windguru#3]

**Comment by KruseLuds** [comment]
(removed)

**Comment by claudobahn** [comment]
Is this happening for every single report cycle or only sometimes?

For me the reporting is working properly, w/ debug=2 I see entries like this:
> Nov 14 16:54:26 weewx4 weewx[1474883] DEBUG user.windguru: {'dateTime': 1668466440, 'usUnits': 1, 'pressure': 29.716, 'outHumidity': 61.0, 'inHumidity': 40.0, 'outTemp': 40.46, 'inTemp': 59.9, 'windSpeed': 10.51, 'windDir': 142.0, 'windGust': 13.65, 'windGustDir': 142.0, 'radiation': 0.0, 'UV': 0.0, 'extraTemp1': 40.46, 'extraTemp2': 39.74, 'extraTemp3': 38.84, 'extraHumid1': 61.0, 'extraHumid2': 73.0, 'extraHumid3': 79.0, 'lightning_strike_count': 0.0, 'altimeter': 30.366305015925075, 'appTemp': 30.43196027314317, 'barometer': 30.388540003381472, 'beaufort': 3.0, 'cloudbase': 3409.2658394124696, 'dewpoint': 28.086030306585133, 'heatindex': 40.46, 'humidex': 40.46, 'inDewpoint': 35.519905386679916, 'maxSolarRad': None, 'rainRate': 0.0, 'windchill': 33.99955203090143, 'interval': 1.0, 'ET': 3.7028324094148876e-05, 'windrun': 0.17516666666666666, 'hourRain': None, 'rain24': None, 'dayRain': None}
Nov 14 16:54:26 weewx4 weewx[1474883] DEBUG user.windguru: url: http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=***&date=14.11.2022&time=16%3A54&temperature=4.7&wind_direction=142&wind_avg=9.1&wind_max=11.9&mslp=1029.074&rh=61.0&interval=1&precip_interval=1

Can you please set your instance to debug=2 and provide relevant excerpts from your own logs that show the call and hopefully include the error response from windguru?

As suggested in the Google group, does seem like there might be a configuration issue on your end, since no data is being sent. Though Why that would only apply to this one publisher, I'm not sure.

**Comment by KruseLuds** [comment]
Ok - thank you for responding so quickly - 

I updated weewx.conf to debug = 2, then

pi@kruse-pi:~$ sudo /etc/init.d/weewx restart

and then immediately

pi@kruse-pi:~$ sudo tail -f /usr/share/hassio/share/weewx.log | grep -E "uru"

resulted in:

pi@kruse-pi:~$ sudo tail -f /usr/share/hassio/share/weewx.log | grep -E "uru"
Nov 15 22:54:28 kruse-pi weewx[285244] DEBUG weewx.restx: Shut down WindGuru thread.
Nov 15 22:54:34 kruse-pi weewx[286087] DEBUG weewx.engine: Loading service user.windguru.WindGuru
Nov 15 22:54:34 kruse-pi weewx[286087] INFO user.windguru: service version is 0.2
Nov 15 22:54:34 kruse-pi weewx[286087] INFO user.windguru: Data will be uploaded for 9-WeewxID-9
Nov 15 22:54:34 kruse-pi weewx[286087] DEBUG weewx.engine: Finished loading service user.windguru.WindGuru
Nov 15 22:55:25 kruse-pi weewx[286087] DEBUG user.windguru: url: http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=22%3A55&interval=5&precip_interval=5
Nov 15 22:55:25 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=22%3A55&interval=5&precip_interval=5'
Nov 15 22:55:25 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 1: Server response: b'ERROR (no data)'
Nov 15 22:55:30 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=22%3A55&interval=5&precip_interval=5'
Nov 15 22:55:30 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 2: Server response: b'ERROR (no data)'
Nov 15 22:55:35 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=22%3A55&interval=5&precip_interval=5'
Nov 15 22:55:36 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 3: Server response: b'ERROR (no data)'
Nov 15 22:55:36 kruse-pi weewx[286087] ERROR weewx.restx: WindGuru: Failed to publish record 2022-11-15 22:55:00 EST (1668570900): Failed upload after 3 tries
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG user.windguru: url: http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A00&interval=5&precip_interval=5
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A00&interval=5&precip_interval=5'
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 1: Server response: b'ERROR (no data)'
Nov 15 23:00:34 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A00&interval=5&precip_interval=5'
Nov 15 23:00:34 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 2: Server response: b'ERROR (no data)'
Nov 15 23:00:39 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A00&interval=5&precip_interval=5'
Nov 15 23:00:40 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 3: Server response: b'ERROR (no data)'
Nov 15 23:00:40 kruse-pi weewx[286087] ERROR weewx.restx: WindGuru: Failed to publish record 2022-11-15 23:00:00 EST (1668571200): Failed upload after 3 tries
Nov 15 23:05:31 kruse-pi weewx[286087] DEBUG user.windguru: url: http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A05&interval=5&precip_interval=5
Nov 15 23:05:31 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A05&interval=5&precip_interval=5'
Nov 15 23:05:32 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 1: Server response: b'ERROR (no data)'
Nov 15 23:05:37 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A05&interval=5&precip_interval=5'
Nov 15 23:05:37 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 2: Server response: b'ERROR (no data)'
Nov 15 23:05:42 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru url: 'http://www.windguru.cz/upload/api.php?stationtype=weewx&uid=9-WeewxID-9&date=15.11.2022&time=23%3A05&interval=5&precip_interval=5'
Nov 15 23:05:42 kruse-pi weewx[286087] DEBUG weewx.restx: WindGuru: Failed upload attempt 3: Server response: b'ERROR (no data)'
Nov 15 23:05:42 kruse-pi weewx[286087] ERROR weewx.restx: WindGuru: Failed to publish record 2022-11-15 23:05:00 EST (1668571500): Failed upload after 3 tries

Around the same time, here are some of the others - that ARE getting data =- 

Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG weewx.restx: Wunderground-PWS url: 'https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php?action=updateraw&ID=##########&PASSWORD=########&softwaretype=weewx-4.9.1&dateutc=2022-11-16%2004%3A00%3A00'
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG user.meteoservices: restx: Meteoservices: Data uploaded to https://channel1.meteo-services.com/stations/index.php is: (b'lat=40.9801519&long=-74.1091612&alt=75.0&stationid=##########&prec_time=60&datum=202211152300&utcstamp=1668571200&rainrate=0.00')
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG user.weather365: restx: Weather365: Data uploaded to https://channel1.weather365.net/stations/index.php is: (b'lat=40.9801519&long=-74.1091612&alt=75.0&stationid=##########&prec_time=60&datum=202211152300&utcstamp=1668571200&rainrate=0.00')
Nov 15 23:00:29 kruse-pi weewx[286087] DEBUG weewx.restx: Weather365: Data uploaded to https://channel1.weather365.net/stations/index.php is: (b'lat=40.9801519&long=-74.1091612&alt=75.0&stationid=##########&prec_time=60&datum=202211152300&utcstamp=1668571200&rainrate=0.00')

Thoughts? How can I debug on the fly - where would the source be and not sure if I would be able to determine this issue - but ?  It worked for a little while. I weas thinking of just reinstalkling Weewx from scratch, but I have alot of customizations  such as moving the weewx log to usr/share/hassio/share/ alopng with the systelog so that Home assistant in a docker container can use it for log scraping etc.... ugh

I can just do a full backup and then try to resintalkl from scratch and just copy over my suctomizations from the backup copy... but then I was thinking what is the problem stll remains?

 Thoughts? There must be a "next step" for debugging.... doe the WindGuru rely upon anything that the others do notr such as some kind of an environment variable that got changed somehow?

What do you think?

**Comment by claudobahn** [comment]
The other uploaders aren't erroring out, but it seems like no data is being provided there, either, they're all only getting meta data, not observational data.

I think you're using an interceptor style setup? You should be seeing log entries for when that data is received. Is any being received, at all? Perhaps the data mapping has a problem? There should be log entries that tell you what data weewx has in its current loop for submission.

**Comment by KruseLuds** [comment]
Yikes I just realized that, I'm going to do a full backup and then uninstall and reinstall (and then just get config files from the backup). Thanks for your help - I am surprised all the other sites don't reject the messages as empty -

**Comment by KruseLuds** [comment]
Nevermind, there is an issue I have already logged [(109)](https://github.com/matthewwall/weewx-interceptor/issues/109) that is the source of this, so closing this for now
